### PR TITLE
Pull in huge amount of upstream changes.

### PR DESCRIPTION
**Pull request by SteveBarnett**
We really should do this more often.

These (250+) commits fix a bunch of issues that we ran into at our most recent RB, and it would be awesome if we can get them in for our next event. It is *a lot* to look through, though... Eep!

### CODE REVIEW

**Comment by rorymckinley** [comment]
Holey smoking metal, Batman :)! I am wondering if it would not be a plan to break the PR up? More overhead, but at least a better chance of getting the changes in? Also, perhaps safer?

I imagine the approach would be to identify where we started to diverge from upstream, and then branch off at points along the mainstream path, and turn these branches into PRs? I am not sure what the git mechanics are around this - would need to do some reading.

Otherwise, if you are not keen on this approach, I am happy to start reviewing this evening, but will have to amortize it over a number of days :)

**Comment by rorymckinley** [comment]
@SteveBarnett have found this - http://stackoverflow.com/questions/13965391/how-do-i-see-the-commit-differences-between-branches-in-git - willing to give me some space to see if I can get this to work out? 

If it is a miserable failure - I will be happy to go with "one PR to find them all, and in the darkness bind them" :)

**Comment by SteveBarnett** [comment]
@rorymckinley You are right: no human should have to deal with a PR like this. I pulled in upstream and then added everything in a blind panic, I think :D. It's beyond my git-fu to know / figure out the best way of doing this, though. I think @wiehann was on to something a few months ago?

Anyway: let's close this PR and figure out a sane way to get all the new commits in. I've played with this "everything pulled in" version on `lolcathost`, and it all looks good. We just need to bring things in a bit more carefully... :)

**Comment by SteveBarnett** [comment]
@rorymckinley I'm going to ask around at the office on Monday and on Teh Internet for some advice about the best way to approach this, while you poke at your link above? Sound good?

**Comment by wiehann** [comment]
@SteveBarnett we have done only the InstallFest sections as there were quite a lot of issues with the InstallFest docs, the last time I attended.  I tested upstream instructions on different virtual machines (Win XP/7/8, Ubuntu Linux, OSX Yosemite/Mavericks/Mountain Lion),  and it worked without a hitch, (unlike the latest we had), so did a diff between our branch and upstream on a per-file basis, merging in their changes.  I created PR's for one or two of the changes that we had made on our side which were merged upstream.

Based on the above, which is quite time consuming - I'd suggest comparing upstream and local docs in a browser, making notes of any parts we might have added/changed (which is either only relevant for RailsBridge-CapeTown or should be PR'd to upstream). Then replace our branch with the latest upstream and use that, re-introduce the noted changes and PR to upstream where necessary.

**Comment by SteveBarnett** [comment]
@wiehann Cool cool cool. Thanks! Rory and I are going to bang heads at the next RB and chat about who can do what and when. :)

**Pull request closed without merging**
