### PR TITLE
remove extra word

### PR DESCRIPTION
**Pull request by dewetb**
Looks like it was a typo or half edited change

I'm very new to any sort of contributing to things on Github. Would it be bad form for me to just press "Merge" on something this straight forward or do people always wait for a thumbs up from someone else on the team?

### CODE REVIEW

**Comment by dewetb** [comment]
I'm very new to any sort of contributing to something on Github. Would it be bad form for me to just press "Merge" on something this straight forward or do people always wait for a thumbs up from someone else on the team?

**Comment by wiehann** [comment]
Not sure. Couldn't hurt to have someone scan through it I guess :)

**Comment by sheldonh** [comment]
One nice side effects on waiting for at least one other person, is that it
encourages contributors to batch up multiple commits into a single pull
request.

**Comment by SteveBarnett** [comment]
@dewetb It depends! :)

In my team at work, we often do a review of a diff of the changes, and make the change directly on `develop` (or `master` for this repo). But there's nothing wrong with small PRs either.

Another thing we do is add a comment like `@Bob: ready for review` if someone specific should look at it.

:+1: Merge the change in.

**Pull request merged**
