### PR TITLE
Add outro activity

### PR DESCRIPTION
**Pull request by SteveBarnett**
Add an outro activity at the end of the course.

One of the questions that comes up a lot is "Now what?" / "What next?"
This is one small step towards trying to help with that.

### CODE REVIEW

**Comment by SteveBarnett** [comment]
Ready for review.

**Comment by rorymckinley** [comment]
You really are churning out the changes @SteveBarnett

**Comment by SteveBarnett** [comment]
@rorymckinley https://www.youtube.com/watch?v=pl3vxEudif8 :)

**Comment by rorymckinley** [comment]
@SteveBarnett Hopefully not a case of this: https://www.youtube.com/watch?v=YoDh_gHDvkk

**Pull request merged**
