### PR TITLE
Rearrange heroku pages

### PR DESCRIPTION
**Pull request by rorymckinley**
* Split into 2 - one for initial deploy and one for every time
* Only show the repeat deploy one as a link (and see if this causes
  issues?)

### CODE REVIEW

**Comment by SteveBarnett** [comment]
@rorymckinley Awesome! Thank you, Rory.

I have one comment, otherwise :+1: .

I was wondering if we should make the first heroku deploy less optional, like this. https://gist.github.com/SteveBarnett/d642bf2b6bd4c14b86c8 

My thinking is that if a students skips those "first time deploy" instructions, the next ones they see are "deploy again" instructions, which could be confusing.
An another approach would be to always have "first time deploy" and "deploy again" at every "Hey, deploy to heroku?" bit, but that seems more complicated that this gist.

**Comment by rorymckinley** [comment]
@SteveBarnett sure, no problem with that at all - will make the change.

**Comment by rorymckinley** [comment]
@SteveBarnett Made the Heroku setup text a bit more Ayn Rand :P

**Comment by SteveBarnett** [comment]
@rorymckinley :+1: , let's get this in before Saturday?

Will you merge and push to Heroku?

**Comment by SteveBarnett** [comment]
Also: thank you! You are made of WIN. :)

**Pull request merged**
